name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza todo dia à meia-noite
  workflow_dispatch:      # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: brendha-barbosa
          outputs: dist/github-contribution-grid-snake.svg
          snake_color: "#FFA500"          # Cor laranja da cobrinha
          background_color: "#00000000"   # Fundo transparente

      - name: Commit e push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando cobrinha animada"
          add: "dist/github-contribution-grid-snake.svg"
